In [1]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

/home/salman/anaconda3/envs/deepl/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
x = torch.rand(3)

In [4]:
print(x)

tensor([0.6864, 0.2846, 0.0250])


In [5]:
x = torch.ones(2,2,dtype=torch.float16)

In [6]:
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [7]:
x = torch.tensor([2.5,0.1])

In [8]:
print(x)

tensor([2.5000, 0.1000])


In [9]:
torch.cuda.is_available()

False

In [10]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [11]:
x

tensor([[0.1090, 0.7268],
        [0.2257, 0.0960]])

In [12]:
y

tensor([[0.3223, 0.2887],
        [0.6349, 0.1777]])

In [13]:
z = x + y

In [14]:
z

tensor([[0.4313, 1.0155],
        [0.8606, 0.2738]])

In [15]:
z = torch.add(x,y)

In [16]:
z

tensor([[0.4313, 1.0155],
        [0.8606, 0.2738]])

In [17]:
y.add_(x)

tensor([[0.4313, 1.0155],
        [0.8606, 0.2738]])

In [18]:
z = x-y

In [19]:
z

tensor([[-0.3223, -0.2887],
        [-0.6349, -0.1777]])

In [20]:
z = torch.sub(x,y)

In [21]:
z

tensor([[-0.3223, -0.2887],
        [-0.6349, -0.1777]])

In [22]:
y.sub(x)

tensor([[0.3223, 0.2887],
        [0.6349, 0.1777]])

In [23]:
z = x*y
z

tensor([[0.0470, 0.7381],
        [0.1942, 0.0263]])

In [24]:
z = torch.mul(x,y)

In [25]:
z

tensor([[0.0470, 0.7381],
        [0.1942, 0.0263]])

In [26]:
z = x/y
z

tensor([[0.2528, 0.7157],
        [0.2623, 0.3507]])

In [27]:
z = torch.div(x,y)
z

tensor([[0.2528, 0.7157],
        [0.2623, 0.3507]])

In [28]:
x = torch.rand(5,3)
x

tensor([[0.0729, 0.0549, 0.1712],
        [0.9789, 0.4536, 0.3973],
        [0.1625, 0.5328, 0.1864],
        [0.8106, 0.0895, 0.2230],
        [0.7265, 0.9541, 0.5748]])

In [29]:
x[:,0]

tensor([0.0729, 0.9789, 0.1625, 0.8106, 0.7265])

In [30]:
import numpy as np

In [31]:
a = torch.ones(5)

In [32]:
a

tensor([1., 1., 1., 1., 1.])

In [33]:
b = a.numpy()

In [34]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [36]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [37]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [38]:
a += 1
a

array([2., 2., 2., 2., 2.])

In [39]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5,device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    z = z.to("cpu")

In [40]:
x = torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [41]:
# AutoGrad

In [42]:
import torch
x = torch.rand(3)
print(x)

tensor([0.0825, 0.3659, 0.0694])


In [43]:
x = torch.rand(3,requires_grad=True)

In [44]:
print(x)

tensor([0.4304, 0.3739, 0.8693], requires_grad=True)


In [45]:
y = x+2
print(y)

tensor([2.4304, 2.3739, 2.8693], grad_fn=<AddBackward0>)


In [46]:
print(x.grad)

None


In [47]:
z = y*y*2
print(z)

tensor([11.8139, 11.2710, 16.4663], grad_fn=<MulBackward0>)


In [48]:
z = z.mean()

In [49]:
print(z)

tensor(13.1837, grad_fn=<MeanBackward0>)


In [50]:
z.backward()

In [51]:
print(x.grad)

tensor([3.2406, 3.1652, 3.8258])


In [52]:
# prevent tracking gradient

In [54]:
x.requires_grad_(False)

tensor([0.4304, 0.3739, 0.8693])

In [55]:
x.detach()

tensor([0.4304, 0.3739, 0.8693])

In [56]:
#with torch.no_grad():

In [57]:
import torch
x = torch.randn(3,requires_grad=True)

In [58]:
x

tensor([ 0.3595, -0.1622, -1.5714], requires_grad=True)

In [59]:
x.requires_grad_(False)

tensor([ 0.3595, -0.1622, -1.5714])

In [60]:
y = x.detach()
y

tensor([ 0.3595, -0.1622, -1.5714])

In [61]:
with torch.no_grad():
    y = x+2
    print(y)

tensor([2.3595, 1.8378, 0.4286])


In [62]:
# example 1 

In [63]:
import torch
weights = torch.ones(4,requires_grad=True)
print(weights)

tensor([1., 1., 1., 1.], requires_grad=True)


In [64]:
for epoch in range(1):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()
    print(weights)

tensor([3., 3., 3., 3.])
tensor([1., 1., 1., 1.], requires_grad=True)


In [65]:
# through optimizer

In [66]:
import torch
weights = torch.ones(4,requires_grad=True)
optimizer = torch.optim.SGD([weights],lr=0.01)
optimizer.step()
optimizer.zero_grad

<bound method Optimizer.zero_grad of SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)>

In [67]:
# Back Propagation

In [68]:
import torch
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0,requires_grad=True)

In [69]:
# Forward Pass

In [70]:
y_hat = w*x
loss = (y_hat-y)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [71]:
# Backward Pass

In [72]:
loss.backward()
print(w.grad)

tensor(-2.)


In [73]:
import tensorflow as tf

In [74]:
tf.__version__

'2.6.2'

In [75]:
torch.version.cuda

'10.2'

In [76]:
!nvid

/bin/bash: line 1: nvid: command not found
