In [1]:
pip install torchvision

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import torchvision
from torch.utils.data import DataLoader,Dataset
import numpy as np
import math

In [3]:
class WineDataset(Dataset):
    def __init__(self):
        xy = np.loadtxt('wine.csv',delimiter=",",dtype=np.float32,skiprows=1)
        self.x = torch.from_numpy(xy[:,1:])
        self.y = torch.from_numpy(xy[:,[0]])
        self.n_samples = xy.shape[0]
    def __getitem__(self,index):
        return self.x[index],self.y[index]
    def __len__(self):
        return self.n_samples

In [4]:
dataset = WineDataset()

In [5]:
first_data = dataset[0]

In [6]:
first_data

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

In [7]:
features, labels = first_data
print(features)
print(labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor([1.])


In [8]:
# Dataloader
dataloader = DataLoader(dataset=dataset,batch_size=4,shuffle=True,num_workers=2)

In [9]:
dataiter = iter(dataloader)

In [10]:
dataiter

In [11]:
data = next(dataiter)

In [12]:
data

[tensor([[1.4100e+01, 2.1600e+00, 2.3000e+00, 1.8000e+01, 1.0500e+02, 2.9500e+00,
          3.3200e+00, 2.2000e-01, 2.3800e+00, 5.7500e+00, 1.2500e+00, 3.1700e+00,
          1.5100e+03],
         [1.2290e+01, 3.1700e+00, 2.2100e+00, 1.8000e+01, 8.8000e+01, 2.8500e+00,
          2.9900e+00, 4.5000e-01, 2.8100e+00, 2.3000e+00, 1.4200e+00, 2.8300e+00,
          4.0600e+02],
         [1.2430e+01, 1.5300e+00, 2.2900e+00, 2.1500e+01, 8.6000e+01, 2.7400e+00,
          3.1500e+00, 3.9000e-01, 1.7700e+00, 3.9400e+00, 6.9000e-01, 2.8400e+00,
          3.5200e+02],
         [1.3240e+01, 2.5900e+00, 2.8700e+00, 2.1000e+01, 1.1800e+02, 2.8000e+00,
          2.6900e+00, 3.9000e-01, 1.8200e+00, 4.3200e+00, 1.0400e+00, 2.9300e+00,
          7.3500e+02]]),
 tensor([[1.],
         [2.],
         [2.],
         [1.]])]

In [13]:
features,labels = data
print(features)
print(labels)

tensor([[1.4100e+01, 2.1600e+00, 2.3000e+00, 1.8000e+01, 1.0500e+02, 2.9500e+00,
         3.3200e+00, 2.2000e-01, 2.3800e+00, 5.7500e+00, 1.2500e+00, 3.1700e+00,
         1.5100e+03],
        [1.2290e+01, 3.1700e+00, 2.2100e+00, 1.8000e+01, 8.8000e+01, 2.8500e+00,
         2.9900e+00, 4.5000e-01, 2.8100e+00, 2.3000e+00, 1.4200e+00, 2.8300e+00,
         4.0600e+02],
        [1.2430e+01, 1.5300e+00, 2.2900e+00, 2.1500e+01, 8.6000e+01, 2.7400e+00,
         3.1500e+00, 3.9000e-01, 1.7700e+00, 3.9400e+00, 6.9000e-01, 2.8400e+00,
         3.5200e+02],
        [1.3240e+01, 2.5900e+00, 2.8700e+00, 2.1000e+01, 1.1800e+02, 2.8000e+00,
         2.6900e+00, 3.9000e-01, 1.8200e+00, 4.3200e+00, 1.0400e+00, 2.9300e+00,
         7.3500e+02]])
tensor([[1.],
        [2.],
        [2.],
        [1.]])


In [14]:
#Training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(total_samples,n_iterations)

178 45


In [15]:
for epoch in range(num_epochs):
    for i,(inputs,labels) in enumerate(dataloader):
        if (i+1)%1==0:
            print(f'epoch {epoch+1}/{num_epochs}, step {i+1}/{n_iterations},inputs {inputs.shape}')

epoch 1/2, step 1/45,inputs torch.Size([4, 13])
epoch 1/2, step 2/45,inputs torch.Size([4, 13])
epoch 1/2, step 3/45,inputs torch.Size([4, 13])
epoch 1/2, step 4/45,inputs torch.Size([4, 13])
epoch 1/2, step 5/45,inputs torch.Size([4, 13])
epoch 1/2, step 6/45,inputs torch.Size([4, 13])
epoch 1/2, step 7/45,inputs torch.Size([4, 13])
epoch 1/2, step 8/45,inputs torch.Size([4, 13])
epoch 1/2, step 9/45,inputs torch.Size([4, 13])
epoch 1/2, step 10/45,inputs torch.Size([4, 13])
epoch 1/2, step 11/45,inputs torch.Size([4, 13])
epoch 1/2, step 12/45,inputs torch.Size([4, 13])
epoch 1/2, step 13/45,inputs torch.Size([4, 13])
epoch 1/2, step 14/45,inputs torch.Size([4, 13])
epoch 1/2, step 15/45,inputs torch.Size([4, 13])
epoch 1/2, step 16/45,inputs torch.Size([4, 13])
epoch 1/2, step 17/45,inputs torch.Size([4, 13])
epoch 1/2, step 18/45,inputs torch.Size([4, 13])
epoch 1/2, step 19/45,inputs torch.Size([4, 13])
epoch 1/2, step 20/45,inputs torch.Size([4, 13])
epoch 1/2, step 21/45,inputs 